Dockerfile, src/loaders/gtdb/gtdb_taxa_freq_loader.py
Never really understood why there were two syntaxes for ENTRYPOINT, and now I really don't understand since one of them will cause signals to not make it to your application.
With the ENTRYPOINT change the container now shuts down immediately rather than waiting for 10 seconds and getting a SIGKILL.
=> Make uvicorn receive SIGTERM

src/service/app.py, src/service/errors.py, src/service/http_bearer.py
For unknown reasons the general error handler wasn't catching HTTPErrors, and in any case I wanted a more informative error than "auth didn't work"
=> Handle authorization errors consistently

Dockerfile, src/service/app.py, test/src/service/app_test.py
Instead use a factory method. This has a couple of benefits:
1. The app isn't created on import
2. in the future we could potentially pass mocks into the create_app function to mock out app dependencies.
=> Don't create app as a global

src/service/errors.py, src/service/models.py, src/service/storage_arango.py
Manual tests below. Also tested error paths, but tests are omitted for length.
```
In [1]: from src.service.storage_arango import create_storage
In [2]: from src.service.models import SavedCollection, ActiveCollection, DataPr
...: oduct
In [3]: import aioarango
In [4]: cli = aioarango.ArangoClient(hosts='http://localhost:8529')
In [5]: db = await cli.db("collections_test")
In [6]: arst = await create_storage(db, create_collections_on_startup=True)
In [7]: sc = SavedCollection(id="foo", name="bar", ver_tag="foobar", ver_src="r2
...: 07", data_products=[DataProduct(product="prod", version="pver")], ver_nu
...: m=65, date_create="iso8601ts", user_create="kbhelp")
In [8]: await arst.save_collection_version(sc)
In [9]: await arst.get_collection_version_by_tag("foo", "foobar")
Out[9]: …
```
=> RE2022-52: Implement save / get collections in arango wrapper.

collections_config.toml.jinja, docker-compose.yaml, src/service/app.py, src/service/config.py, src/service/models.py
Sets up the DB connection as is now required.
```
In [1]: from src.service.storage_arango import create_storage
In [2]: from src.service.models import SavedCollection, ActiveCollection, DataPr
...: oduct
In [3]: import aioarango
In [4]: cli = aioarango.ArangoClient(hosts='http://localhost:8529')
In [5]: db = await cli.db("collections_test")
In [6]: arst = await create_storage(db, create_collections_on_startup=True)
In [7]: ac = ActiveCollection(id="foo", name="bar", ver_tag="foobar", ver_src="r
...: 207", data_products=[DataProduct(product="prod", version="pver")], ver_n
...: um=65, date_create="iso8601ts", user_create="kbhelp", date_active="iso86
...: 01ts2", user_active="user2")
In [8]: await arst.save_collection_active(ac)
In [9]: ac.name = 'whoo'
In [10]: ac.id = 'whee'
In [11]: await …
```
=> Add a /collections endpoint to the service.

src/service/app.py, src/service/routes_collections.py
Will allow adding data products endpoints before the collections admin endpoints
Also simplifies method metadata declarations slightly
=> Split up collections router

src/service/routes_collections.py
=> Consistently use `data` key to wrap a returned list

src/service/data_product_specs.py, src/service/data_products/common.py, src/service/data_products/taxa_count.py, src/service/storage_arango.py
Two data products sharing the same collection names would be bad
=> Prevent collection collisions

src/service/data_products/genome_attributes.py
Paging through records with skip & limit is O(n^2), so
10000 = 100M ops
100000 = 10B ops
Also, 10K is the ElasticSearch default, so we're in good company with that value.
=> Drop skip max to 10000

src/service/data_products/genome_attributes.py
It's punishing everyone who gets the sort field right with an extra query. Just check the sort field after the regular query (since arango doesn't complain) and throw an error then.
=> Don't check sort field before query

src/service/data_product_specs.py, src/service/data_products/genome_attributes.py, src/service/matcher_registry.py, src/service/matchers/common_models.py, src/service/matchers/lineage_matcher.py, src/service/routes_collections.py
Returns information about matchers avialable in the service. Useful for people adding matchers to collections
=> RE2022-78: Add matchers endpoint

src/common/storage/collection_and_field_names.py, src/common/storage/db_doc_conversions.py, src/service/matchers/lineage_matcher.py, src/service/models.py, src/service/storage_arango.py, test/src/loaders/genome_collection/compute_genome_taxa_count_test.py
Also make internal_match_id a standard field for taxa counts so the matches can be stored in the same collection
Also also add a bulk update helper method which will be needed when inserting taxa_count records
=> RE2022-98: Add data product match structure & arango methods

src/service/data_products/genome_attributes.py, src/service/data_products/taxa_count.py, src/service/match_processing.py, src/service/matchers/lineage_matcher.py
1. Make the MatchProcess class handle the asyncio stuff rather than making the implementer of the matcher do it. Now they just have to implement an async function with the right args.
2. Simplify the API for running through a genome attributes match slightly.
3. Fix a potential, although unlikely, race condition when matching
4. Fix a bug when a `None` or empty fields list is supplied to `process_match_documents`
=> Small bugfixes & simplifications

collections_config.toml.jinja, src/service/app.py, src/service/app_state.py, src/service/config.py, src/service/data_products/genome_attributes.py, src/service/data_products/taxa_count.py, src/service/http_bearer.py, src/service/routes_collections.py
While working on the dead process restart feature, I ran into a couple problems:
* `matcher_registry` imports were winding up everywhere in order to get matchers to rerun match processes. This lead to circular imports all over as well.
* I was having to pass in storage, workspace, pickleable deps, and matcher dependencies to some of the new methods, which was making the method signatures huge.
To fix this I refactored dependency handling into a state class that can be passed around and used to get dependencies as needed. I added the matchers to that class so that the matcher registry only needs to be imported at the top level of the app and the matchers passed into the state builder, which breaks the import loops.
=> Refactor dependencies into class

src/common/storage/collection_and_field_names.py, src/service/models.py, src/service/storage_arango.py
```python
In [1]: from src.service.data_product_specs import DATA_PRODUCTS
In [2]: from src.service.storage_arango import ArangoStorage
In [3]: from src.service import models
In [4]: import aioarango
In [5]: cli = aioarango.ArangoClient(hosts='http://localhost:8529')
In [6]: db = await cli.db("collections_test", username="root", password="foobar"
...: )
In [7]: dps = {dp.data_product: dp.db_collections for dp in DATA_PRODUCTS.values
...: ()}
In [8]: arst = await ArangoStorage.create(db, dps)
In [9]: match_id = "ff1d36301008ace844e77b8a7698273c"
In [10]: # got above from match already existing in DB
In [11]: mtch = await arst.get_match_full(match_id)
In [12]: mtch
Out[12]: InternalMatch(match_id='ff1d36301008ace844e77b8a7698273c', matcher_id='gtdb_lineage', collection_id='GTDB', …
```
=> RE2022-85: Add DB methods for adding, getting, and removing deleted matches

Pipfile, Pipfile.lock, src/service/match_deletion.py, src/service/storage_arango.py, test/src/service/match_deletion_test.py
```
In [1]: from src.service.config import CollectionsServiceConfig
In [2]: from src.service import app_state
In [3]: from src.service.data_product_specs import DATA_PRODUCTS
In [4]: from src.service.match_deletion import MatchCleanup
In [5]: def mc():
...:     with open('./collections_config.toml', 'rb') as f:
...:         cfg = CollectionsServiceConfig(f)
...:     dps = {dp.data_product: dp.db_collections for dp in DATA_PRODUCTS.va
...: lues()}
...:     pd = app_state.PickleableDependencies(cfg, dps)
...:     mc = MatchCleanup(pd, 10, 5, 24 * 60 * 60 * 1000)
...:     mc.start()
...:     return mc
...:
In [6]: matchc = mc()
In [7]: # taken from a match in the DB:
In [8]: 1677714146688 - (24 * 60 * 60 * 1000)
Out[8]: 1677627746688
In [9]: # save this value back to the DB in last_access
In …
```
=> RE2022-85: Delete match & related data

src/service/_app_state_build_storage.py, src/service/app.py, src/service/app_state.py, src/service/app_state_data_structures.py, src/service/data_product_specs.py, src/service/data_products/taxa_count.py, src/service/match_deletion.py, src/service/match_retrieval.py, src/service/matchers/lineage_matcher.py, src/service/processing.py, src/service/routes_collections.py
* Made the data product registry load data products on request rather than at import time to break import cycles. Now we can reference the data product registry in various places without import loops.
* Split up app_state to allow importing subparts of the state and avoiding import loops.
=> Refactor to break import loops

src/loaders/jobs/taskfarmer/task_generator.py
add global task info file so that we can look up job ids attached to each task. NERSC only caches job status for a certain period of time.
=> add global task info file

src/common/storage/collection_and_field_names.py, src/service/errors.py, src/service/models.py, src/service/storage_arango.py
```python
In [1]: from src.service.storage_arango import ArangoStorage
f
In [2]: from src.service import data_product_specs
In [4]: from src.service import models
In [5]: import aioarango
In [6]: cli = aioarango.ArangoClient(hosts='http://localhost:8529')
In [7]: db = await cli.db("collections_test", username="root", password="foobar"
...: )
In [8]: dps = {dp.data_product: dp.db_collections for dp in data_product_specs.g
...: et_data_products()}
In [9]: arst = await ArangoStorage.create(db, dps)
In [10]: sa = models.ActiveSelection(
...:     selection_id_hash="super_secure",
...:     active_selection_id="some_id",
...:     internal_selection_id="foo",
...:     last_access=42
...:     )
In [11]: await arst.save_selection_active(sa)
In [12]: await arst.get_selection_active("super_secure") …
```
=> RE2022-115: Add selection manipulation methods to the DB layer

src/service/models.py, src/service/routes_collections.py, src/service/storage_arango.py
Also DRY up the 3 state update methods.
=> RE2022-116: Add selection state update method

src/common/storage/collection_and_field_names.py, src/common/storage/db_doc_conversions.py, src/service/storage_arango.py
Also effectively defines the database structure for the type information for a data product.
```python
In [1]: from src.common.storage import collection_and_field_names as names
In [2]: from src.service.storage_arango import ArangoStorage
In [3]: from src.service import data_product_specs
In [4]: from src.common.storage.db_doc_conversions import data_product_export_ty
...: pes_to_doc
In [5]: import aioarango
In [6]: cli = aioarango.ArangoClient(hosts='http://localhost:8529')
In [7]: db = await cli.db("collections_test", username="root", password="foobar"
...: )
In [8]: dps = {dp.data_product: dp.db_collections for dp in data_product_specs.g
...: et_data_products()}
In [9]: arst = await ArangoStorage.create(db, dps)
In [10]: doc = data_product_export_types_to_doc("GTDB", …
```
=> RE2022-137 Get type info for a data product

src/common/storage/collection_and_field_names.py
make the name non-type specific so we can use the same global key in non-genome contexts
We'll need to reprocess and reload all the data when this change goes live on CI.
=> Change `kbase_genome_id` -> `kbase_id`

src/service/data_products/common_functions.py, src/service/data_products/common_models.py, src/service/data_products/genome_attributes.py, src/service/data_products/taxa_count.py, src/service/matcher_registry.py, src/service/matchers/lineage_matcher.py, src/service/processing.py, src/service/processing_matches.py, src/service/processing_selections.py, src/service/storage_arango.py
Makes it easier to reuse code between primary matches / selections & secondary m/ss, since secondary m/ss only keep the internal ID in the DB record (as they should)
Also infinitesimally safer since the process will only write to the m/s they were started against and will fail if that m/s is deleted rather than writing to a new m/s (which should never happen, but...)
Also also makes the `CollectionProcess` class a little saner since the internal ID can be provided to gtdb_lineage matcher right away rather than having to wait for the matcher to calculate it and provide it to the process `start() ` method later
Finally, move the match API parameter specifications into a shared location for reuse with heatmaps
=> RE2022-143: Use internal IDs for managing match / sel processes

Pipfile, Pipfile.lock, src/service/data_products/common_models.py, src/service/data_products/genome_attributes.py, src/service/data_products/heatmap.py, src/service/data_products/taxa_count.py
Just checking that it now works after the fastapi 0.95.1 release. From now on use the `Annotated` stycle and covert old style params over when touching them,
=> Start switch to `Annotated` param definitions

src/service/data_products/heatmap.py, src/service/models.py, src/service/storage_arango.py
It's to be expected that not all data sources will have microtrait data, or the data required to calculated it, available.
Next step is to allow the client to retrive the missing IDs.
=> RE2022-148: Store missing IDs rather than fail on heatmap match / select

src/service/routes_collections.py
Silly to have a different admin endpoint for both. Also lines up with the regular endpoint.
=> RE2022-179: Move match / selection deletion under `admin`

src/loaders/jobs/taskfarmer/taskfarmer_task_mgr.py
Resolve the issue occurring when the taskfarmer is called for the first time.
=> fix non-exist folder bug

src/common/storage/collection_and_field_names.py, src/loaders/common/loader_common_names.py, src/loaders/genome_collection/parse_tool_results.py, src/loaders/workspace_downloader/workspace_downloader.py, src/service/data_products/genome_attributes.py
Some of the loader names are used or will need to be used in the service, so moved them to the common names file.
=> Move shared names to common names

src/common/storage/collection_and_field_names.py, src/loaders/workspace_downloader/workspace_downloader.py, src/service/data_products/common_models.py, src/service/data_products/genome_attributes.py, src/service/data_products/heatmap.py, src/service/data_products/table_models.py, src/service/data_products/taxa_count.py
Also update shared query specfiers to the new `Annotated` syntax before reusing them with samples
=> RE2022-203: Factor out genome attribs models for reuse

src/service/data_products/data_product_processing.py, src/service/data_products/genome_attributes.py, src/service/data_products/heatmap.py, src/service/data_products/table_models.py
Move the method that determines the applicable load version and either gets or starts the match and selection processes to common module for reuse with samples.
Also just put the match and selection prefixes in one place for now
=> RE2022-203: Move subset processing method from heatmap for reuse

src/common/product_models/heatmap_common_models.py
Could be used for things other than the media in the future
=> RE2022-232: Add metadata per heatmap row for biolog media

src/service/storage_arango.py
```python
In [1]: import aioarango
In [2]: from src.service.storage_arango import ArangoStorage
In [3]: from src.common.collection_column_specs import load_specs
In [4]: from src.service.filtering import analyzers
In [5]: cli = aioarango.ArangoClient(hosts='http://localhost:8529')
In [6]: db = await cli.db("collections_test", username="root",
password="foobar"
...: )
In [7]: store = await ArangoStorage.create(db)
In [8]: view_spec = load_specs.load_spec("genome_attribs")
In [9]: try:
...:     await store.create_search_view("view_name2",
"kbcoll_genome_attribs"
...: , view_spec, analyzers.get_analyzer)
...: except Exception as e:
...:     print(e)
...:
The view 'view_name2' already exists and differs from the requested
specification.
In [10]: await store.create_search_view("new_view", …
```
=> RE2022-240: Add arango wrapper functions for dealing with arangosearch views

src/common/collection_column_specs/genome_attribs-GTDB.yml, src/common/collection_column_specs/genome_attribs-PMI.yml, src/common/product_models/columnar_attribs_common_models.py, src/service/data_products/common_functions.py, src/service/data_products/genome_attributes.py, src/service/filtering/filters.py, test/src/common/collection_column_specs/load_specs_test.py, test/src/service/filtering/analyzers_test.py, test/src/service/filtering/filters_test.py
`load_ver` shouldn't be exposed to users here and `coll` is redundant. Also remove the `inarray` filter strategy as arangosearch treats arrays and strings effectively identically when it comes to matching, so there's no need for it
=> Remove internal fields from genome attribs meta endpoint

src/loaders/workspace_downloader/workspace_downloader_helper.py
without explicitly provide `CALLBACK_IP`, the jobrunner container will return an ipv6 address. 
But the JobRunner code should return an IPV4 instead. I am not sure if it has something to do with how the image was built (there is no dockerfile in that repo). 
https://github.com/kbase/JobRunner/blob/master/JobRunner/JobRunner.py#L202-L204
```
(base) tgu@login39 tgu  $ podman run --name tian_callback -it --rm \
> --net host \
> -e KB_* \
> -e CALLBACK_PORT=9999 \
> -e KB_AUTH_TOKEN=$KB_AUTH_TOKEN \
> -e KB_BASE_URL=https://ci.kbase.us/services/ \
> -e JOB_DIR \
> -e DEBUG_MODE=true \
> -v $JOB_DIR:$JOB_DIR \
> kbase/callback:test
WARN[0000] Path "/etc/SUSEConnect" from "/etc/containers/mounts.conf" doesn't exist, skipping 
WARN[0000] Path "/etc/zypp/credentials.d/SCCcredentials" from …
```
=> explicitly provide ipv4 to callback server

src/service/data_products/genome_attributes.py, src/service/filtering/filters.py, test/src/service/filtering/filters_test.py
as well as ArangoSearch. This'll allow us to put the table search aql generation code in one place instead of the current 3 and abstract away the difference between arangosearch and regular queries.
Next step is updating the code to use the filterset everywhere tables are queried.
=> Refactor filters.py to generate AQL

src/service/processing_selections.py, src/service/routes_collections.py, src/service/workspace_wrapper.py
... as per /design/provenance.md
Also throw an error if the description is > 800 chars
Match information is still do do
=> RE2022-268: Add basic provenance information when saving sets

src/service/app_state.py, src/service/processing_selections.py, src/service/routes_collections.py
Match details are added to the set provenance
Still do to: add default parameters to the user submitted parameters when saving the match. Currently default parameters are excluded
=> RE2022-268: Allow specifying a match when saving a selection as a workspace set

docs/data_pipeline_procedure.md
after running those two comments on /global/cfs/cdirs/kbase/collections, tested rerun tools and parsers, all newly generated files are on kbase group now.
=> RE2022-263, RE2022-271: set default file group

src/service/filtering/filters.py, test/src/service/filtering/filters_test.py
Filter out any keep data to prevent nulls showing up in data intended for plots and causing pydantic to complain, resulting in a 500.
Pt 2 is integrating this into the genome utils data product.
=> Fix 500 error when plot data contains nulls pt1

src/service/data_products/genome_attributes.py
Apply filters null filter in genome attribs plot endpoints
Manually tested David's failure mode with the hist and scatter endpoints with and without a filter included in the query
=> Fix 500 error when plot data contains nulls pt2

src/loaders/common/loader_helper.py, src/loaders/genome_collection/parse_PMI_biolog_data.py, src/loaders/genome_collection/parse_tool_results.py
transformed heatmap_data looks like:
{"kbase_id": "69037_10_1", "col_1_cell_id": "efe9dc0c-39c8-48d2-88ea-4fd93de5ec0c", "col_1_val": 0, "col_2_cell_id": "f5145e84-d370-4b1d-9906-edc58d4725ef", "col_2_val": 3, "col_3_cell_id": "a5fb45d9-e42e-44e6-821e-a418fb11e33d", "col_3_val": 0, "col_4_cell_id": "a2f1c72f-7515-4c77-83d9-4cd7b7e04256", "col_4_val": 0, "col_5_cell_id": "4677ebb4-328a-493d-9baa-370f60d9afa3", "col_5_val": 0, "col_6_cell_id": "b7b84f0a-55d3-4b65-a0ec-9ddb0fa138f6", "col_6_val": 0, "col_7_cell_id": "bd0f5d06-1322-44f9-b222-6524075ab095", "col_7_val": 2, ... ...
=> RE2022-275: reconstruct heatmap row cells

src/service/matchers/lineage_matcher.py, src/service/models.py
comparing to fuzzy matching approach, we need to re-active all collections if we do it this way.
=> RE2022-294: relax gtdb version matching

src/common/collection_column_specs/genome_attribs-GTDB.yml, src/common/collection_column_specs/genome_attribs-PMI.yml
example genome_attribs_meta:
```
{"columns": [{"key": "fastani_af", "type": "float", "filter_strategy": null, "display_name": "FastANI AF", "category": "Other", "description": null, "min_value": 0.76, "max_value": 0.76, "enum_values": null}, {"key": "Completeness", "type": "float", "filter_strategy": null, "display_name": "CheckM Completeness", "category": "Quality", "description": null, "min_value": 76.76, "max_value": 98.07, "enum_values": null}, {"key": "fastani_reference", "type": "string", "filter_strategy": "identity", "display_name": "FastANI Reference", "category": "Other", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "closest_placement_reference", "type": "string", "filter_strategy": "identity", "display_name": "Closest Placement …
```
=> RE2022-300: add display name and category for genome attrib

src/common/collection_column_specs/parse_sample_template.py, src/common/collection_column_specs/samples-ENIGMA.yml
A bug found during creating search view - spec entries need to be identical across different collections.
=> RE2022-320: fix spec file bug

src/common/product_models/columnar_attribs_common_models.py, src/service/data_products/common_functions.py, src/service/data_products/genome_attributes.py, src/service/data_products/samples.py
example local curl of the new endpoint.
```
(dev) tgu@collections (dev_sample_filtering)$curl -X 'GET' \
'http://127.0.0.1:5000/collections/ENIGMA/data_products/samples/meta' \
-H 'accept: application/json' | python -m json.tool
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  3174  100  3174    0     0   393k      0 --:--:-- --:--:-- --:--:--  774k
{
"columns": [
{
"key": "kbase_display_name",
"type": "string",
"filter_strategy": "ngram",
"non_visible": false,
"display_name": "KBase Name",
"category": "Identifiers",
"description": null,
"min_value": null,
"max_value": null,
"enum_values": null
},
{
"key": "longitude",
"type": "float",
"filter_strategy": null,
"non_visible": false,
"display_name": "Longitude", …
```
=> RE2022-320: add sample meta endpont

src/service/data_products/data_product_processing.py, src/service/data_products/heatmap.py, src/service/data_products/samples.py
example local endpoint call:
```
(dev) tgu@collections (dev_sample_filtering)$curl -X 'GET' \
'http://127.0.0.1:5000/collections/ENIGMA/data_products/samples/?output_table=false&limit=1&filter_genome_count=%5B3,4%5D' \
-H 'accept: application/json' \
-H "Authorization: Bearer $token" | python -m json.tool
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   487  100   487    0     0   1407      0 --:--:-- --:--:-- --:--:--  1419
{
"match_state": null,
"selection_state": null,
"skip": 0,
"limit": 1,
"fields": null,
"table": null,
"data": [
{
"enigma:date": "2014-06-17",
"enigma:experiment_name": "Groundwater",
"enigma:time_zone": "UTC\u221204:00",
"enigma:well_name": "DP16D",
"env_package": "water",
"genome_count": …
```
=> RE2022-320: add update samples filter set to enable filtering

src/loaders/common/loader_helper.py
We need to make sure the parser script does create a meta spec with the 'non_visible' field.
=> include non_visible field for parser script

src/service/data_products/taxa_count.py
example local endpoint return:
default sort:
```
(dev) tgu@collections (dev_taxa_count_ordering)$curl -X 'GET' \
"$server_url/collections/PMI/data_products/taxa_count/counts/$rank/?match_id=$match_id&status_only=false" \
-H 'accept: application/json' \
-H "Authorization: Bearer $token" | python -m json.tool
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   333  100   333    0     0  26232      0 --:--:-- --:--:-- --:--:-- 33300
{
"match_state": "complete",
"selection_state": null,
"data": [
{
"name": "Actinomycetota",
"count": 82,
"match_count": 82,
"sel_count": null
},
{
"name": "Pseudomonadota",
"count": 367,
"match_count": 0,
"sel_count": null
},
{
"name": "Bacteroidota",
"count": 53,
"match_count": 0, …
```
=> RE2022-327: add default sort taxa count

src/loaders/workspace_uploader/workspace_uploader.py, test/src/loaders/workspace_uploader/workspace_uploader_test.py
An overwrite for the 'file_name' will happen when uploading multiple files using the previous structure.
=> RE2022-328: update uploaded.yaml file struct

src/common/collection_column_specs/genome_attribs-GTDB.yml, src/common/collection_column_specs/genome_attribs-PMI.yml, src/common/collection_column_specs/samples-ENIGMA.yml, src/common/collection_column_specs/samples-GROW.yml, src/common/product_models/columnar_attribs_common_models.py, src/loaders/common/loader_helper.py, test/src/common/collection_column_specs/load_specs_test.py
example generated genome_attrbs.jsonl  file.
```
{"kbase_id": "69037_2_1", "Contamination": 0.85, "Completeness": 88.28, "_key": "6c95a1d46e809f84063dccf93700ffa9", "coll": "GROW", "load_ver": "tian_test_taskfarmer", "_mtchsel": [], "user_genome": "69037_2_1_kbase", "classification": "d__Bacteria;p__Verrucomicrobiota;c__Verrucomicrobiae;o__Chthoniobacterales;f__Chthoniobacteraceae;g__Chth-196;s__", "fastani_reference": null, "fastani_reference_radius": null, "fastani_taxonomy": null, "fastani_ani": null, "fastani_af": null, "closest_placement_reference": "GCA_945883955.1", "closest_placement_radius": 95.0, "closest_placement_taxonomy": "d__Bacteria;p__Verrucomicrobiota;c__Verrucomicrobiae;o__Chthoniobacterales;f__Chthoniobacteraceae;g__Chth-196;s__Chth-196 sp945883955", …
```
=> add no_cast to _mtchsel

RELEASE_NOTES.md, src/common/version.py, src/service/filtering/filters.py, test/src/service/filtering/filters_test.py
The classic mistake of thinking since you control the fields you can just use dot notation. Nope, some sample fields have colons in them which borks things up.
=> Safe filter fields in AQL
