- .github/workflows/manual-build.yml
- .github/workflows/pr_build.yml
- .github/workflows/release-main.yml
- Dockerfile
GHAs were installed from the KBase repo via the Github UI
> Add GHA builds and a minimal Dockerfile

- service/app.py
The docs UI expects to be served at /docs, not
/services/collectionsservice/docs/, which screws things up
> Fix docs UI

- .gitignore
- src/service/arg_checkers.py
- src/service/errors.py
- src/service/kb_auth.py
- src/service/user.py
- test/src/service/arg_checkers_test.py
- test/src/service/errors_test.py
- test/src/service/kb_auth_test.py
- test/src/service/user_test.py
input checkers, errors, user ID, etc.
Some of this stuff maybe should be moved to common but we can cross that bridge when we come to it.
> Add basic infrastructure for auth & service

- Pipfile
- Pipfile.lock
- src/service/kb_auth.py
```
In [1]: with open('/home/<user>/.kbase_token_ci') as f:
...:     token = f.read().strip()
...:
In [2]: from src.service.kb_auth import KBaseAuth
In [3]: ka = KBaseAuth("https://ci.kbase.us/services/auth", ["ws_read_admin"], c
...: ache_expiration=5)
In [4]: ka.get_user(token)
Out[4]: (<AdminPermission.FULL: 10>, UserID("gaprice"))
In [8]: ka = KBaseAuth("https://ci.kbase.us/services/auth", ["ws_fake_admin"], c
...: ache_expiration=5)
In [9]: ka.get_user(token)
Out[9]: (<AdminPermission.NONE: 1>, UserID("gaprice"))
```
> Add auth client

- src/service/app.py
- src/service/errors.py
Will probably need extension as we add functionality
> Add error handling framework

- src/service/app.py
- src/service/http_bearer.py
Just do all the auth in one place
> Simplify authorization handling

- README.md
- test/src/service/config_test.py
- test/src/service/http_bearer_test.py
Should probably have a corresponding test file for each module
> Add missing noop tests

- README.md
- src/service/app.py
Embed in error key so it's clear it's an error, add server time stamp
> Refine error structure

- src/service/arg_checkers.py
- src/service/models.py
- test/src/service/models_test.py
very slightly tested manually for now. If we start finding too many bugs when running the service I'll add a test suite.
> Add collection pydantic model

- collections_config.toml.jinja
- src/service/app.py
- src/service/config.py
- src/service/models.py
- src/service/storage_arango.py
also close arango client properly
> Option to not connect to ext services

- Pipfile
- Pipfile.lock
- src/service/app.py
- src/service/models_errors.py
Also handle 404 errors correctly
> Document error structure

- src/service/app.py
- src/service/models.py
Turns out that getting the collection version was just a suboperation of activation, so added those too
> Add collection version activation routes

- README.md
- src/service/app.py
- src/service/routes_collections.py
- src/service/storage_arango.py
- src/service/timestamp.py
- test/src/service/timestamp_test.py
Main app file was getting too unwieldy
> Factor out routes from main app

- docker-compose.yaml
- src/service/config.py
Arango with auth hasn't been tested yet
> Fix writelines typo

- src/service/app.py
- src/service/routes_collections.py
- src/service/storage_arango.py
No way to figure out what inactive collections are available otherwise
> Add endpoints to get collection IDs

- src/common/hash.py
- src/loaders/gtdb/gtdb_genome_stats_loader.py
- src/loaders/gtdb/gtdb_taxa_freq_loader.py
- src/service/storage_arango.py
- test/src/common/hash_test.py
> DRY up md5 handling

- README.md
- src/common/storage/collection_and_field_names.py
- src/loaders/gtdb/gtdb_genome_stats_loader.py
- src/loaders/gtdb/gtdb_taxa_freq_loader.py
- src/service/app.py
- src/service/storage_arango.py
- test/src/loaders/gtdb/gtdb_genome_stats_loader_test.py
- test/src/loaders/gtdb/gtdb_taxa_freq_loader_test.py
Need to have the loaders and service speak the same language wrt collection names and fields
> RE2022-55: Document collection names / fields in `common`

- src/service/routes_collections.py
- src/service/routes_common.py
- test/src/conftest.py
- test/src/service/routes_common_test.py
for reuse in data product routes
> RE2022-55: Factor out common routes constructs

- src/common/storage/collection_and_field_names.py
- src/service/app.py
- src/service/app_state.py
- src/service/data_product_specs.py
- src/service/data_products/common.py
This will almost certainly change as I implement the first data product, but it's a reasonable starting point
> RE2022-55: Add a minimal framework for adding data products

- src/service/app_state.py
- src/service/data_products/common.py
- src/service/storage_arango.py
Not really tested other than making sure the server starts up and creates indexes correctly. Will test when a DP is added
> RE2022-55: Add support for data products to arango wrapper

- src/loaders/gtdb/gtdb_taxa_count_loader.py
- test/src/loaders/gtdb/gtdb_taxa_count_loader_test.py
The data is counts, not frequency
> RE2022-55: Rename taxa_freq loader to taxa_count

- .gitignore
- src/common/storage/collection_and_field_names.py
- src/loaders/gtdb/gtdb_genome_attribs_loader.py
- src/service/data_product_specs.py
- src/service/data_products/common_functions.py
- src/service/data_products/genome_attributes.py
- src/service/data_products/taxa_count.py
- test/src/loaders/gtdb/gtdb_genome_attribs_loader_test.py
Needed to unmunge the loader keys as arango doesn't like whitespace in keys
> Add genome_attribs data product

- src/service/data_products/genome_attributes.py
> Just use built in defaults vs coding them

- src/service/data_products/genome_attributes.py
Default to table since the payload is ~1/2 the size
> Add an optional table format for genome attributes return

- docs/adding_data_products.md
- src/service/app.py
- src/service/data_products/genome_attributes.py
- src/service/data_products/taxa_count.py
Avoid collisions with non-data product related paths
> Add data_products prefix to paths

- src/service/app.py
- src/service/errors.py
- src/service/workspace_wrapper.py
- test/src/service/workspace_wrapper_test.py
Hide the annoying details of the WS API from the rest of the code
> RE2022-83: Add a workspace wrapper

- src/service/errors.py
- src/service/models.py
- src/service/routes_collections.py
- src/service/storage_arango.py
Will be needed for the workspace permissions check coming up next.
> RE2022-83: Add user permissions check to model

- src/service/models.py
- src/service/routes_collections.py
- src/service/storage_arango.py
Also index the match last accessed date
> RE2022-83: Add match creation date to model

- src/service/app_state.py
- src/service/match_processing.py
- src/service/matcher_registry.py
- src/service/matchers/lineage_matcher.py
- src/service/routes_collections.py
- src/service/storage_arango.py
Pydantic models don't pickle in some cases - it appears to have something to do with the validation function. Required some refactoring.
> RE2022-83: Run match process in separate process

- src/service/matchers/lineage_matcher.py
- src/service/models.py
- src/service/storage_arango.py
Targeted toward the API layer which shouldn't get internal match data
> RE2022-83: Add get_match method to storage

- src/common/storage/collection_and_field_names.py
- src/loaders/genome_attributes/loader_helper.py
- src/service/app_state.py
- src/service/data_products/genome_attributes.py
- src/service/match_processing.py
- src/service/matchers/lineage_matcher.py
- src/service/models.py
- src/service/routes_collections.py
- src/service/storage_arango.py
Also some minor prep for matching and refactoring of pickable dependencies
> RE2022-83: Add set match state to arango storage

- src/service/data_products/common_functions.py
- src/service/data_products/genome_attributes.py
- src/service/errors.py
- src/service/match_processing.py
- src/service/models.py
- src/service/storage_arango.py
... and get matching results back
> RE2022-83: Submit match ID to genome attribs

- .gitignore
- src/common/gtdb_lineage.py
- src/common/storage/collection_and_field_names.py
- src/common/storage/db_doc_conversions.py
- src/loaders/genome_collection/compute_genome_taxa_count.py
- test/src/common/gtdb_lingeage_test.py
> RE2022-98: Factor out taxa count calcs & doc conversion

- src/loaders/common/loader_helper.py
ensure the `kbase_genome_id` field exist
> ensure kbase_genome_id field 

- src/service/data_products/genome_attributes.py
- src/service/data_products/taxa_count.py
- src/service/match_retrieval.py
- src/service/matcher_registry.py
- src/service/matchers/lineage_matcher.py
- src/service/processing.py
- src/service/routes_collections.py
match specific to non-specific
> Refactor processing code for reuse

- Pipfile
- Pipfile.lock
- src/service/data_products/taxa_count.py
- src/service/matchers/lineage_matcher.py
- src/service/processing.py
Tested by adding an asyncio.sleep(100) statement to the match process and watching the match record in arango
Next:
* When a standard match or data product match is pulled from the DB, check the last heart beat and restart the process if it's beyond the threshold
> RE2022-89: Add a heartbeat to match processes

- README.md
- src/service/app_state.py
- src/service/data_products/taxa_count.py
- src/service/match_retrieval.py
- src/service/processing.py
- src/service/routes_collections.py
- src/service/storage_arango.py
A little bit of refactoring for testability and code reuse in match deletion.
* Refactoring the processing code slightly to reuse in deletions.
* Made timestamp generation more easily mockable.
* Also laid out rules for displaying timestamps to API clients.
> Pre match deletion refactoring

- src/service/match_deletion.py
- src/service/storage_arango.py
Next: actually delete all the match data
```python
In [1]: from src.service.match_deletion import MatchCleanup
In [2]: from src.service import app_state
In [3]: from src.service.config import CollectionsServiceConfig
In [4]: from src.service.data_product_specs import DATA_PRODUCTS
In [5]: with open('./collections_config.toml', 'rb') as f:
...:     cfg = CollectionsServiceConfig(f)
...:
In [6]: dps = {dp.data_product: dp.db_collections for dp in DATA_PRODUCTS.values
...: ()}
In [7]: def mc():
...:     pd = app_state.PickleableDependencies(cfg, dps)
...:     mc = MatchCleanup(pd, 10, 5, 24 * 60 * 60 * 1000)
...:     mc.start()
...:     return mc
...:
In [8]: # taken from a match in the DB:
In [9]: 1677458286548 - (24 * 60 * 60 * 1000)
Out[9]: 1677371886548
In [10]: # save this value back to …
```
> RE2022-85: Move matches to a deleted state

- src/service/app.py
- src/service/app_state.py
- src/service/match_deletion.py
Tested manually by creating a match and then altering its `last_access` field to be a week in the past.
> RE2022-85: Integrate match deletion into service

- src/service/routes_collections.py
If there are multiple paths to the same object, drop all exept the shortest. If there's more than one with the shortest length, take the first.
> Ignore duplicate objects in match input

- src/service/match_retrieval.py
* skip blank strings
* error if any parts of the UPA are < 1
> Fix UPA processing bugs

- src/service/data_products/genome_attributes.py
- src/service/match_retrieval.py
- src/service/matcher_registry.py
- src/service/matchers/lineage_matcher.py
- src/service/models.py
- src/service/routes_collections.py
Only real matcher is gtdb_lineage for now
Next - truncate lineages with rank parameter
> RE2022-97: Send user params for matchers to matcher

- src/service/routes_collections.py
Still need to fire off the process that actually marks things as selected
> RE2022-115: Create selection

- src/service/models.py
- src/service/routes_collections.py
- src/service/selection_processing.py
- src/service/tokens.py
... in preparation to add process creation
> RE2022-116: refactor selection handling into module

- src/common/storage/collection_and_field_names.py
- src/loaders/common/loader_helper.py
- src/service/data_products/genome_attributes.py
- src/service/matchers/lineage_matcher.py
Will allow for AND / ORing matches and selections with an index
> RE2022-116: Store genome attribs match and selection marks in same field

- src/common/storage/collection_and_field_names.py
- src/service/data_products/taxa_count.py
- src/service/match_deletion.py
- src/service/match_retrieval.py
- src/service/models.py
- src/service/storage_arango.py
- test/src/service/match_deletion_test.py
... for matches and selections
> RE2022-117: Refactor to share data product arango code

- src/service/data_products/taxa_count.py
- src/service/match_retrieval.py
- src/service/storage_arango.py
to allow for both match and selection processing
> RE2022-117: Refactor data product processing

- src/service/data_products/taxa_count.py
- src/service/match_retrieval.py
- src/service/processing.py
to general processing class from match specific class
> RE2022-117: Move data product processing method

- src/service/data_products/taxa_count.py
- src/service/processing_matches.py
- src/service/routes_collections.py
now it's in its forever home <3
> Move match processing code to processing_matches.py

- src/service/data_products/genome_attributes.py
Only alter the count if they're set up to filter the main results
> RE2022-130: Don't alter counts if match/selections are just marks

- src/service/data_products/taxa_count.py
- src/service/deletion.py
- src/service/models.py
- src/service/storage_arango.py
- test/src/service/deletion_test.py
Useful outside of the context of processes
> RE2022-117: Rename ProcessType -> SubsetType

- src/service/data_products/genome_attributes.py
Looks like I never tested without a match ID, doh
It's starting to get to a point where prototype or no, we probably need to start adding some tests
> RE2022-116: Fix selection id bug

- src/loaders/jobs/taskfarmer/task_generator.py
- src/loaders/jobs/taskfarmer/taskfarmer_task_mgr.py
there shouldn't be any case where we want to overwrite batch scripts if they exist, though I think if they are identical it won't affect anything.
> avoid overwritting files

- Pipfile
- Pipfile.lock
- src/service/app_state_data_structures.py
- src/service/sdk_async_client.py
```python
In [1]: with open('/home/crushingismybusiness/.kbase_token_ci') as f:
...:     citoken = f.read().strip()
...:
In [2]: from src.service.sdk_async_client import SDKAsyncClient
In [3]: sdkcli = SDKAsyncClient("https://ci.kbase.us/services/ws")
In [4]: await sdkcli.call("Workspace.ver")
Out[4]: '0.14.1-dev1'
In [5]: await sdkcli.call("Workspace.get_object_info3", [{"objects": [{"ref": "6
...: 8953/12/1"}]}], token=citoken)
Out[5]:
{'infos': [[12,
'lineage_correct_bacillus_A_anthracis',
'KBaseGenomeAnnotations.Assembly-6.0',
'2023-03-09T00:56:24+0000',
1,
'gaprice',
68953,
'gaprice:narrative_1674687340883',
'42d1b600409f75c97333f87c51323a9c',
51273,
None]],
'paths': [['68953/12/1']]}
In [6]: await sdkcli.call("Workspace.get_object_info3", [{"objects": [{"ref": "6
...: …
```
> RE2022-101: Add a minimal async SDK client

- src/common/storage/collection_and_field_names.py
- src/service/data_products/genome_attributes.py
> RE2022-137: Switch field name containing UPA info

- src/loaders/jobs/docker_img/Dockerfile.checkm2
- src/loaders/jobs/taskfarmer/task_generator.py
FixedCheckm2 image and validated through successful execution of a Taskfarmer job.
> fix checkm2 image

- src/common/storage/collection_and_field_names.py
- src/loaders/common/loader_helper.py
- src/loaders/gtdb/gtdb_genome_attribs_loader.py
- src/service/data_products/common_functions.py
- src/service/data_products/common_models.py
- src/service/data_products/genome_attributes.py
- test/src/loaders/gtdb/gtdb_genome_attribs_loader_test.py
...in heatmaps. The queries are going to be very similar, although not identical.
> RE2022-141: Refactor genome attribs queries for reuse

- src/service/app_state.py
... by closing the SDK and arango clients regardless of the error.
> Handle startup errors correctly

- src/service/data_products/heatmap.py
> RE2022-141: split up `HeatmapController.__init__`

- .gitignore
- src/service/data_products/common_functions.py
- src/service/data_products/genome_attributes.py
- src/service/data_products/heatmap.py
Can now be used by the heatmap code for selection and match marking
> RE2022-143: Refactor genome attribs selection for general use

- src/service/data_products/common_functions.py
- src/service/data_products/genome_attributes.py
> RE2022-143: Refactor subset removal function for reuse

- src/service/data_products/common_models.py
- src/service/data_products/heatmap.py
- src/service/data_products/taxa_count.py
Save a little bandwidth
Closes #212
> Add `status_only` flag to taxa_counts

- src/service/data_products/heatmap.py
- src/service/data_products/heatmap_common_models.py
Return IDs that weren't found in a match or selection
> RE2022-148: Add `missing` endpoint to heatmap

- src/loaders/compute_tools/microtrait/Dockerfile
- src/loaders/compute_tools/microtrait/env_microtrait.yaml
- src/loaders/compute_tools/microtrait/microtrait.py
Will port over the changes in https://github.com/kbase/collections/pull/268 when that's merged in (in a future PR)
> Add microtrait to ToolRunner setup

- src/common/product_models/heatmap_common_models.py
- src/loaders/genome_collection/parse_tool_results.py
- src/service/data_products/heatmap.py
Updated the load data manually with `sed` and tested the service.
@Tianhao-Gu - do you think you could test the parser script when you have a chance?
> RE2022-176: Make heatmap field names more readable & consistent

- src/loaders/common/loader_common_names.py
- src/loaders/compute_tools/microtrait/microtrait.py
- src/loaders/compute_tools/microtrait/microtrait_util.py
Add detected gene and it's score to trait_count.csv file. 
sample result file content
> RE2022-156: add detected gene score to trait count table

- src/service/app.py
I assumed this was built in, I guess not
> Support gzipped responses

- src/loaders/compute_tools/microtrait/Dockerfile
- src/loaders/compute_tools/microtrait/microtrait_util.py
confirmed no missing unwrapped rules for all traits in granularity1, 2 and 3.
> RE2022-156: retrieve rules by substrate

- src/loaders/workspace_downloader/workspace_downloader.py
This PR address [this comment](https://kbase.slack.com/archives/C03FK9RKSBX/p1685660960874599)
> multiple genomes pointing to the same assembly in Enigma

- src/loaders/common/loader_common_names.py
- src/loaders/compute_tools/microtrait/microtrait.py
- src/loaders/genome_collection/parse_tool_results.py
This PR address [this comment](https://kbase.slack.com/archives/C03FK9RKSBX/p1686075502548529) in Slack
> Fix engima

- Pipfile
- Pipfile.lock
- README.md
- src/common/storage/init_storage.py
> RE2022-194: Finish collection init script

- src/service/_app_state_build_storage.py
Was introduced when adding the CLI for creating collections
> Fix server startup bug

- src/common/storage/collection_and_field_names.py
- src/service/data_products/common_models.py
- src/service/data_products/genome_attributes.py
- src/service/data_products/heatmap.py
- src/service/data_products/taxa_count.py
... and the special match and selection fields
> RE2022-23: Reuse genome attribs query validators for samples

- src/service/data_products/common_functions.py
- src/service/data_products/genome_attributes.py
- src/service/data_products/heatmap.py
& share code with genome attribs and heatmaps
> RE2022-203: Refactor count methods for reuse in samples

- src/loaders/compute_tools/tool_common.py
avoid adding all dependencies from loader_helper for all images.
> RE2022-177: fix import requirments

- src/service/data_products/common_functions.py
- src/service/data_products/genome_attributes.py
- src/service/data_products/heatmap.py
- src/service/data_products/samples.py
... and refactor table code for reuse
> RE2022-203: Add samples table to API

- design/experiments/benchmarking_mash_vs_sourmash.md
> RE2022-222: Add benchmark for mash on separate sketches

- Pipfile
- Pipfile.lock
- design/experiments/benchmark_sourmash_signature_storage.md
- design/experiments/store_mongo.py
Next: pull them out and search them
> RE2022-222: Store sourmash sketches in mongo

- src/service/models.py
- src/service/storage_arango.py
> RE2022-212: Add attribution field to collections

- src/service/data_products/samples.py
- src/service/data_products/table_models.py
- src/service/data_products/taxa_count.py
- src/service/models.py
- src/service/routes_collections.py
In some cases optional fields need to be Annotated and explicitly assigned, and some cases they don't. I'm not quite sure which is which yet.
> Fix bugs related to pydantic 2 conversion

- design/genome_attributes_filtering.md
- src/common/product_models/columnar_attribs_common_models.py
- src/common/storage/collection_and_field_names.py
- src/service/data_products/genome_attributes.py
> RE2022-239: Add genome attribs metadata endpoint to service

- design/experiments/arangosearch_views.md
for full text and substring search
> RE2022-240: Add arangosearch timings & notes

- design/experiments/arangosearch_views.md
Currently no major difference between `LIKE()` (which requires an index scan) and n-gram search, probably due to the DB size. However, n-gram search handles tokens in the search string while `LIKE()` can't.
> RE2022-240: Add timings for n-gram substring search

- src/service/data_products/filtering.py
- test/src/service/data_products/filtering_test.py
Parses the input range filter specification and translates to ArangoSearch AQL.
> RE2022-240: Add range filtering representation code

- design/genome_attributes_filtering.md
* Use arangosearch for all filtering ops
* Note n-gram might be useful for substring search
* Note decision to not add any infrastructure for updating indexes / views
> RE2022-240: Update filtering design doc

- src/common/product_models/columnar_attribs_common_models.py
- src/service/data_products/filtering.py
- test/src/service/data_products/filtering_test.py
Represents a filter for a string column and translates to ArangoSearch AQL lines.
> RE2022-240: Add a string filter representation class

- src/service/data_products/filtering.py
- test/src/service/data_products/filtering_test.py
Needed prior to any integration into the service
> RE2022-240: Add load_ver, skip, and limit to arangosearch AQL generator

- src/common/storage/collection_and_field_names.py
- src/service/app_state.py
- src/service/filtering/analyzers.py
- src/service/filtering/filters.py
- src/service/storage_arango.py
- test/src/service/filtering/analyzers_test.py
> RE2022-240: Install prefix search analyzer on startup

- src/loaders/genome_collection/parse_PMI_biolog_data.py
- src/loaders/genome_collection/parse_tool_results.py
address bugs mentioned in https://kbase.slack.com/archives/C03FK9RKSBX/p1695146211301439
> fix biolog data pipeline bugs

- src/common/collection_column_specs/genome_attribs-GTDB.yml
- src/common/collection_column_specs/genome_attribs-PMI.yml
- src/common/collection_column_specs/test_dp-COL1.yml
- src/common/collection_column_specs/test_dp-COL2.yml
- src/common/product_models/columnar_attribs_common_models.py
- src/service/filtering/analyzers.py
- src/service/filtering/filters.py
- test/src/common/collection_column_specs/load_specs_test.py
- test/src/service/filtering/analyzers_test.py
- test/src/service/filtering/filters_test.py
Def need to index the coll, load_ver, and _mtchsel columns in arangosearch
> RE2022-240: Add global columns to column specs

- src/service/data_products/common_models.py
- src/service/data_products/genome_attributes.py
- src/service/models.py
- src/service/storage_arango.py
Will be used when configuring a new view
```python
In [1]: import aioarango
In [2]: from src.service.storage_arango import ArangoStorage
In [3]: from src.service.models import DynamicConfig
In [4]: cli = aioarango.ArangoClient(hosts='http://localhost:8529')
In [5]: db = await cli.db("collections_test", username="root",
password="foobar"
...: )
In [6]: store = await ArangoStorage.create(db)
In [7]: await store.get_dynamic_config()
Out[7]: DynamicConfig(search_views={})
In [8]: await
store.update_dynamic_config(DynamicConfig(search_views={"foo":"bar
...: "}))
Out[8]: DynamicConfig(search_views={'foo': 'bar'})
In [9]: await
store.update_dynamic_config(DynamicConfig(search_views={"foo":"bar
...: 2", "baz": "bat"}))
Out[9]: DynamicConfig(search_views={'foo': 'bar2', 'baz': 'bat'})
In [10]: …
```
> RE2022-240: Add method to update dynamic config

- src/service/filtering/filters.py
- src/service_manager.py
- test/src/service/filtering/filters_test.py
Variables declared in filters shouldn't be marked as bind variables
> RE2022-240: Fix filter aql bug

- src/service/data_products/genome_attributes.py
- src/service/models.py
Still needs a number of features from standard lookups like matches, count, etc.
> RE2022-240: Implement basic arangosearch filtering

- src/common/collection_column_specs/genome_attribs-PMI.yml
- src/common/product_models/columnar_attribs_common_models.py
- src/loaders/common/loader_helper.py
- src/loaders/genome_collection/parse_tool_results.py
- src/loaders/gtdb/gtdb_genome_attribs_loader.py
- test/src/loaders/gtdb/gtdb_genome_attribs_loader_test.py
example output jsonl:
`{"columns": [{"key": "classification_method", "type": "string", "filter_strategy": "fulltext", "min_value": null, "max_value": null, "enum_values": null}, {"key": "Contamination", "type": "float", "filter_strategy": null, "min_value": 0.05, "max_value": 2.3, "enum_values": null}, {"key": "closest_placement_radius", "type": "float", "filter_strategy": null, "min_value": 95.0, "max_value": 95.0, "enum_values": null}, {"key": "fastani_reference_radius", "type": "float", "filter_strategy": null, "min_value": 0.0, "max_value": 0.0, "enum_values": null}, {"key": "closest_placement_reference", "type": "string", "filter_strategy": "identity", "min_value": null, "max_value": null, "enum_values": null}, {"key": "Completeness", "type": "float", "filter_strategy": null, …
> RE2022-244: create genome attributes meta import files

- src/service/data_products/genome_attributes.py
- src/service/filtering/analyzers.py
> RE2022-240: Add filtering API documentation

- src/service/data_products/common_functions.py
- src/service/data_products/genome_attributes.py
- src/service/data_products/heatmap.py
- src/service/data_products/samples.py
Cleans up very similar code in several places
> Refactor all table queries to use FilterSet

- src/loaders/compute_tools/gtdb_tk/gtdb_tk.py
- src/loaders/compute_tools/gtdb_tk/versions.yaml
skip ani_screen step to improve performance.
> RE2022-247: skip ani screen step

- src/common/collection_column_specs/genome_attribs-GTDB.yml
- src/common/collection_column_specs/genome_attribs-PMI.yml
- src/common/product_models/columnar_attribs_common_models.py
- src/service/data_products/genome_attributes.py
- src/service/filtering/analyzers.py
- src/service/filtering/filters.py
- test/src/common/collection_column_specs/load_specs_test.py
- test/src/service/filtering/analyzers_test.py
- test/src/service/filtering/filters_test.py
... and apply it to the classification field
> RE2022-246: Add ngram based string matching

- docker-compose.yaml
- src/service/filtering/filters.py
- test/src/service/filtering/filters_test.py
Make the match non-fuzzy
Also bump arango to 3.11 in the dockerfile
> RE2022-246: Set ngram threshold to 1

- src/service/data_products/genome_attributes.py
> Trivial xyscatter docs fix

- src/common/product_models/heatmap_common_models.py
- src/loaders/common/loader_helper.py
- src/loaders/genome_collection/parse_PMI_biolog_data.py
- src/loaders/genome_collection/parse_tool_results.py
- src/service/data_products/heatmap.py
Results from local testing after inserting new data for Microtrait and Biolog match precisely with those from the CI server.
> Feature heatmap filtering

- src/common/product_models/columnar_attribs_common_models.py
- src/service/data_products/common_models.py
- src/service/data_products/heatmap.py
- src/service/filtering/generic_view.py
- src/service/models.py
- src/service/storage_arango.py
- src/service_manager.py
local created view for microtrait:
`
{
"writebufferSizeMax": 33554432,
"id": "27714",
"storedValues": [],
"name": "m1",
"type": "arangosearch",
"consolidationPolicy": {
"type": "tier",
"segmentsBytesFloor": 2097152,
"segmentsBytesMax": 5368709120,
"segmentsMax": 10,
"segmentsMin": 1,
"minScore": 0
},
"writebufferActive": 0,
"links": {
"kbcoll_microtrait_data": {
"analyzers": [
"identity"
],
"fields": {
"kbase_display_name": {
"analyzers": [
"kbcoll_en_ngram3"
]
}
},
"includeAllFields": true,
"storeValues": "none",
"trackListPositions": false
}
},
"commitIntervalMsec": 1000,
"consolidationIntervalMsec": 1000,
"globallyUniqueId": "hEED053C208E7/27714",
"cleanupIntervalStep": 2,
"primarySort": [],
"primarySortCompression": "lz4",
"writebufferIdle": 64
}
`
> RE2022-275: create search view for biolog/microtrait

- src/service/data_products/common_functions.py
- src/service/data_products/data_product_processing.py
- src/service/data_products/samples.py
* Update indexes
* Update main sample return method to handle matches and selections
* Update get samples by ID method to handle flattened samples
* Update get missing IDs method to handle flattened samples
* Update get samples by location method to handle flattened samples
> RE2022-290: Sample flattening

- src/common/storage/collection_and_field_names.py
- src/loaders/common/loader_helper.py
- src/loaders/genome_collection/parse_tool_results.py
- src/loaders/gtdb/gtdb_genome_attribs_loader.py
example of generated samples meta for ENIGMA collection.
```
{"columns": [{"key": "kbase_display_name", "type": "string", "filter_strategy": "ngram", "non_visible": false, "display_name": "KBase Name", "category": "Identifiers", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "longitude", "type": "float", "filter_strategy": null, "non_visible": false, "display_name": "Longitude", "category": "Geolocation", "description": "Longitude of the location where the sample was collected in WGS 84 coordinate system.", "min_value": -84.33630514999999, "max_value": -84.27208199999997, "enum_values": null}, {"key": "enigma:date", "type": "date", "filter_strategy": null, "non_visible": false, "display_name": "Date", "category": "Collection", "description": "Date …
```
> RE2022-320: refactor parser to create sample meta data

- src/service/data_products/common_functions.py
- src/service/data_products/genome_attributes.py
- src/service/data_products/samples.py
Not all sample entries in the DB have the same keys, which can mean the table view of the samples table may have out of order columns for samples with missing keys. Fill in missing values with `null`.
> RE2022-330: Fix missing sample table entries bug

- src/service/data_products/common_functions.py
Previous change to specified fields left out the special match and selection fields
> Fix match / selections bug

- RELEASE_NOTES.md
- src/common/version.py
All changes reviewed in prior PRs.
> Develop -> Main (0.1.0 release)
